version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  licensor:
    image: licensor:dev
    restart: always 
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_DATABASE: licensor_db
    ports:
      - 127.0.0.1:8080:8080

volumes:
  postgres-data:
    driver: local
